export interface GoodItem {
  id: number
  goodsName: string
  goodImg: string
  goodPrice: number
  goodCount: number

}

export const listinfo:GoodItem[]=[
  {
    id: 1,
    goodsName: "班俏BANQIAO超火ins潮卫衣女士2020秋季新款韩版宽松慵懒风薄款外套带帽上衣",
    goodImg: "/assets/1.webp",
    goodPrice: 108,
    goodCount: 1
  },
  {
    id: 1,
    goodsName: "嘉叶希连帽卫衣女春秋薄款2020新款宽松bf韩版字母印花中长款外套ins潮",
    goodImg: "/assets/2.webp",
    goodPrice: 108,
    goodCount: 1
  },
  {
    id: 1,
    goodsName: "思蜜怡2020休闲运动套装女春秋季新款时尚大码宽松长袖卫衣两件套",
    goodImg: "/assets/3.webp",
    goodPrice: 108,
    goodCount: 1
  },
  {
    id: 1,
    goodsName: "班俏BANQIAO超火ins潮卫衣女士2020秋季新款韩版宽松慵懒风薄款外套带帽上衣",
    goodImg: "/assets/4.webp",
    goodPrice: 108,
    goodCount: 1
  },
  {
    id: 1,
    goodsName: "思蜜怡卫衣女加绒加厚2020秋冬装新款韩版宽松上衣连帽中长款外套",
    goodImg: "/assets/5.webp",
    goodPrice: 108,
    goodCount: 1
  },
  {
    id: 1,
    goodsName: "班俏BANQIAO超火ins潮卫衣女士2020秋季新款韩版宽松慵懒风薄款外套带帽上衣",
    goodImg: "/assets/6.webp",
    goodPrice: 108,
    goodCount: 1
  },
  {
    id: 1,
    goodsName: "班俏BANQIAO超火ins潮卫衣女士2020秋季新款韩版宽松慵懒风薄款外套带帽上衣",
    goodImg: "/assets/7.webp",
    goodPrice: 108,
    goodCount: 1
  },
  {
    id: 1,
    goodsName: "班俏BANQIAO超火ins潮卫衣女士2020秋季新款韩版宽松慵懒风薄款外套带帽上衣",
    goodImg: "/assets/8.webp",
    goodPrice: 108,
    goodCount: 1
  },
  {
    id: 1,
    goodsName: "班俏BANQIAO超火ins潮卫衣女士2020秋季新款韩版宽松慵懒风薄款外套带帽上衣",
    goodImg: "/assets/9.webp",
    goodPrice: 108,
    goodCount: 1
  },
  {
    id: 1,
    goodsName: "班俏BANQIAO超火ins潮卫衣女士2020秋季新款韩版宽松慵懒风薄款外套带帽上衣",
    goodImg: "/assets/10.webp",
    goodPrice: 108,
    goodCount: 1
  },
]